---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
    ansible_distribution: centos
  when: ansible_distribution == "RedHat"

- name: copy file hids-ossec-agent
  copy:
    src: files/ossec-hids-client-{{ ossec_centos_release_version }}.rpm
    dest: /tmp/ossec-hids-client.rpm

- name: install hids-ossec-agent
  yum:
    name: /tmp/ossec-hids-client.rpm
    state: present
